name: example
nodes:
  - id: node1
    dependencies: []
    inputs:
      - name: num1
        description: Description of num1
        type: Float
        reference: num1
      - name: num2
        description: Description of num2
        type: Float
        reference: num2
    outputs:
      - name: sum
        type: Float
    action: function_to_call1
    failure: failure_function1
    onfailure: false
    description: Description of node1
    timeout: 3600  # 1 hour in seconds
    try_count: 3

  - id: node2
    dependencies: 
      - "node1"
    inputs:
      - name: result
        description: Description of result (referencing sum of node1)
        type: Float
        reference: node1.sum
    outputs:
      - name: squared_result
        type: Float
    action: function_to_call2
    failure: failure_function2
    onfailure: true
    description: Description of node2
    timeout: 1800  # 30 minutes in seconds
    try_count: 2

  - id: node3
    dependencies: 
      - "node2"
    inputs:
      - name: result
        description: Description of result (referencing squared_result of node2)
        type: Float
        reference: node2.squared_result
    outputs:
      - name: doubled_result
        type: Float
      - name: puta
        type: String  
    action: function_to_call3
    failure: failure_function3
    onfailure: false
    description: Description of node3
    timeout: 3600  # 1 hour in seconds
    try_count: 3
