[package]
name = "simple_task"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
dagger = { path = "../.." }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
serde_json = "1.0" 